server:
  port: 8081

spring:
  docker:
    compose:
      file: ./authentication/docker-compose.yml
  kafka:
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      bootstrap-servers: localhost:9092
  profiles:
    active: production
  datasource:
    url: jdbc:postgresql://localhost:5433/ecommerce-auth
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  application:
    name: authentication
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true