server:
  port: 8080

spring:
  docker:
    compose:
      file: ./authentication/docker-compose.yml
  datasource:
    url: jdbc:postgresql://localhost:5432/e-commerce
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  application:
    name: authentication
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka