#services:
##  auth:
##    container_name: auth_service
##    build: ./authentication
##    env_file:
##      - ./env/postgres.env
##      - ./env/pgadmin.env
#
#  db:
#    container_name: auth-db
#    image: postgres
#    env_file:
#      - ./env/postgres.env
#    ports:
#      - "5432:5432"
#  pgadmin:
#    container_name: pgadmin
#    image: dpage/pgadmin4
#    env_file:
#      - ./env/pgadmin.env
#    ports:
#      - "5050:80"
#    restart: unless-stopped