services:
  category-db:
    container_name: categories-db
    image: postgres
    env_file:
      - ../env/categories.env
    ports:
      - "5434:5432"
  pgadmin:
    container_name: pgadmin-categories
    image: dpage/pgadmin4
    env_file:
      - ../env/categories.env
    ports:
      - "5051:80"
    restart: unless-stopped