timife:
  kafka:
    topic: token.published
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
    enabled: true
spring:
  application:
    name: gateway-service
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: authentication
          uri: lb://authentication
          predicates:
            - Path=/auth/**
          filters:
            - AuthenticationFilter
server:
  port: 8088
