server:
  port: 8083
order:
  kafka:
    topic: order.published

spring:
  cloud:
#    discovery:
#      client:
#        simple:
#          instances:
#            INVENTORY[0]:
#              uri: http://INVENTORY
#            AUTHENTICATION[0]:
#              uri: https://AUTHENTICATION
    loadbalancer:
      enabled: true
  docker:
    compose:
      file: ./cart/docker-compose.yml
  kafka:
    bootstrap-servers: localhost:9092
  datasource:
    url: jdbc:postgresql://localhost:5435/ecommerce-cart
    password: secret
    username: timife
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  application:
    name: cart
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true