server:
  port: 8084
payment:
  kafka:
    topic: payment.published

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: "app-username/email"
    password: "smtp-app-password"
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
  docker:
    compose:
      file: ./payment/docker-compose.yml
  kafka:
    bootstrap-servers: localhost:9092
  datasource:
    url: jdbc:postgresql://localhost:5436/ecommerce-payment
    password: secret
    username: timife
  profiles:
    active: production
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  application:
    name: payment