server:
  port: 8081

spring:
  docker:
    compose:
      file: ./docker-compose.yml
  profiles:
    active: production
  datasource:
    url: jdbc:postgresql://localhost:5432/e-commerce
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  application:
    name: categories
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true