version: '3'
services:
  auth-db:
    container_name: auth-postgres-db
    image: postgres
    env_file:
      - ../env/auth.env
    ports:
      - "5433:5432"
    networks:
      - kafka-network
  pgadmin:
    container_name: auth-pgadmin
    image: dpage/pgadmin4
    env_file:
      - ../env/auth.env
    ports:
      - "5050:80"
    restart: unless-stopped
    networks:
      - kafka-network

networks:
  kafka-network:
    external: true